import Head from "next/head";
import React from "react";
import Typography from "@mui/material/Typography";
import LoadingButton from "@mui/lab/LoadingButton";

import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Box from "@mui/material/Box";
import TextField from "@mui/material/TextField";
import Button from "@mui/material/Button";
import SendIcon from "@mui/icons-material/Send";
import CardContent from "@mui/material/CardContent";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [formInput, setFormInput] = React.useState("");
  const [result, setResult] = React.useState("");
  const [isLoading, setIsLoading] = React.useState(false);
  const handleSubmit = (evt: any) => {
    // if (!formInput) alert("Input empty");
    evt.preventDefault();
    console.log({ formInput });
    setResult("");
    setIsLoading(true);
    fetch("/api/openai", {
      method: "POST",
      body: JSON.stringify(formInput),
      headers: {
        "Content-Type": "application/json",
      },
    })
      .then((response) => response.json())
      .then((response) => {
        console.log("Success:", JSON.stringify(response));
        setResult(response);
        setIsLoading(false);
      })
      .catch((error) => console.error("Error:", error));
  };
  const handleInput = (evt: any) => {
    const newValue = evt.target.value;
    setFormInput(newValue);
  };

  return (
    <Box>
      <Head>
        <title>Mail AI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box sx={{ width: "80%", m: "auto", mt: 2 }}>
        <Box sx={{ mb: 2 }}>
          <Typography variant="subtitle1" component="div" color={"#1d3557"}>
            Try Mail AI:
          </Typography>
        </Box>
        <Box>
          <form onSubmit={handleSubmit}>
            <TextField
              fullWidth
              label="Type your email here"
              id="fullWidth"
              multiline
              onChange={handleInput}
              variant="outlined"
              minRows={6}
            />

            <Box sx={{ mt: 1, width: "8px" }}>
              <LoadingButton
                variant="contained"
                endIcon={<SendIcon />}
                type="submit"
                loading={isLoading}
              >
                Send
              </LoadingButton>
            </Box>
          </form>
        </Box>
        <Box
          sx={{
            bgcolor: "#457b9d",
            borderRadius: "8px",
            color: "white",
            pl: 1,
            mt: 4,
            height: "auto",
            minHeight: "300px",
          }}
        >
          <Typography
            variant="subtitle1"
            component="div"
            sx={{
              textDecoration: "underline",
            }}
          >
            Result:
          </Typography>
          <Typography
            sx={{
              fontSize: 16,
              color: "white",
              px: 2,
            }}
            color="text.secondary"
            gutterBottom
          >
            {result}
          </Typography>
        </Box>
      </Box>
    </Box>
  );
}
